### ISSUE TITLE
Supported ultrasonic development boards

### ISSUE THREAD

**Issue by kk9six** [tdk-invn-oss/ultrasonic.arduino.CHx01#1]
Hi,

Does it only support the part of DK-x0201 at the moment?
What about the part of DK-CH101? Because it seems that DK-x0201 is for the ICU-x0201 sensors while DK-CHx01 is for CHx01 sensors?

Regards,
Kun

**Comment by rbuisson-invn** [comment]
Hello kk9six,

The [DK-x0201](https://invensense.tdk.com/products/dk-x0201/) can also be used for CH101 & CH201.
The wiring is described on the library page:  https://github.com/tdk-invn-oss/ultrasonic.arduino.CHx01

Regards,
